# adaptor file for ansible-webobjects-role
# Here goes all the Wonder Apache <-> WebObjects adaptor related tasks
---
- name: 'ADAPTOR | Check if {{ wo_name }} adaptor is already installed'
  stat:
    path: '/usr/lib64/httpd/modules/mod_WebObjects.so'
  register: wo_adaptor_mod

- block:
  - name: 'ADAPTOR | Ensure wonder temporary dir exists'
    file:
      path: '/tmp/wonder'
      state: directory

  - name: 'ADAPTOR | Clone wonder repository in a temporary folder'
    unarchive:
      src: '{{ wonder_download_url }}'
      dest: '/tmp/wonder'
      remote_src: True
      extra_opts:
        - '--strip-components=1'

  - name: 'ADAPTOR | Configure WO Adaptor to always log'
    lineinfile:
      path: '/tmp/wonder/Utilities/Adaptors/Adaptor/config.h'
      search_string: '/* #define ALWAYS_LOG */'
      line: '#define ALWAYS_LOG'
    when: wo_always_log == True

  - name: 'ADAPTOR | Configure WO Adaptor to always log'
    lineinfile:
      path: '/tmp/wonder/Utilities/Adaptors/Adaptor/config.h'
      search_string: '//#define ALWAYS_LOG */'
      line: '#define ALWAYS_LOG'
    when: wo_always_log == True

  - name: 'ADAPTOR | Configure Make to produce Linux compatible binaries of WO Adaptor'
    lineinfile:
      path: '/tmp/wonder/Utilities/Adaptors/make.config'
      regexp: '^ADAPTOR_OS\s='
      line: 'ADAPTOR_OS = LINUX'

  - name: 'ADAPTOR | Configure Make to produce Apache 2.4 compatible binaries of WO Adaptor'
    lineinfile:
      path: '/tmp/wonder/Utilities/Adaptors/make.config'
      regexp: '^ADAPTORS\s=\sCGI\sApache2\.2'
      line: 'ADAPTORS = Apache2.4'

  - name: 'ADAPTOR | Build {{ wo_name }} adaptor for Apache 2.4'
    make:
      chdir: '/tmp/wonder/Utilities/Adaptors'

  - name: 'ADAPTOR | Install {{ wo_name }} adaptor as an Apache module'
    command: 'apxs -i -a -n WebObjects mod_WebObjects.la'
    args:
      chdir: '/tmp/wonder/Utilities/Adaptors/Apache2.4'

  - name: 'ADAPTOR | Remove wonder temporary directory'
    file:
      path: '/tmp/wonder'
      state: absent
  when: wo_adaptor_mod.stat.exists == False

- name: 'ADAPTOR | Copy {{ wo_name }} Apache configuration to {{ web_config_dir }}'
  template:
    src: 'apache.conf.j2'
    dest: '{{ web_custom_config_dir }}/webobjects.conf'
    owner: 'root'
    group: 'root'
    mode: 0644
  notify: restart_httpd

- name: 'ADAPTOR | Remove ScriptAlias cgi-bin'
  lineinfile:
    path: '{{ web_config_dir }}/httpd.conf'
    regexp: '^ScriptAlias /cgi-bin/'
    state: absent
  notify: restart_httpd
