# configure file for ansible-webobjects-role
# All configurations of WebObjects and System scripts should go here!
---
- name: 'CONFIG | Configure WebObjects apps on SiteConfig.xml'
  template:
    src: 'SiteConfig.xml.j2'
    dest: "{{ wo_basedir }}/config/SiteConfig.xml"
    owner: "{{ wo_user }}"
    group: "{{ wo_user_group }}"
    mode: 0644

- name: 'CONFIG | Configure WebObjects apps on WOConfig.xml'
  template:
    src: 'WOConfig.xml.j2'
    dest: "{{ wo_basedir }}/config/WOConfig.xml"
    owner: "{{ wo_user }}"
    group: "{{ wo_user_group }}"
    mode: 0644

- name: 'CONFIG | Create WebObjects WOTaskD SystemD unit'
  template:
    src: 'wotaskd.service.j2'
    dest: "/etc/systemd/system/wotaskd.service"
    owner: 'root'
    group: 'root'
    mode: 0755
  when: wo_install_wotaskd == True
  notify: restart_wotaskd_service

- name: 'CONFIG | Create WebObjects JavaMonitor SystemD unit'
  template:
    src: 'javamonitor.service.j2'
    dest: "/etc/systemd/system/javamonitor.service"
    owner: 'root'
    group: 'root'
    mode: 0755
  when: wo_install_javamonitor == True
  notify: restart_javamonitor_service
