---
- name: 'DEPLOY | Create {{ wo_name }} related directories'
  file:
    path: '{{ item }}'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ wo_basedir }}/tools'
    - '{{ wo_basedir }}/apps'
    - '{{ wo_basedir }}/config'
    - '{{ wo_logdir }}'
    - '{{ wo_logdir }}/gc'
    - '{{ wo_logdir }}/heapdumps'

- name: 'DEPLOY | Create directory for {{ wo_name }} web resources'
  file:
    path: '{{ wo_webdir }}'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: directory
    mode: 0755

