---
- name: 'JavaMonitor | Check if JavaMonitor is already installed'
  stat:
    path: '{{ wo_basedir }}/tools/JavaMonitor.woa'
  register: javamonitor_dir

- block:
  - name: 'JavaMonitor | Download latest version of JavaMonitor'
    unarchive:
      src: '{{ java_monitor_download_url }}'
      dest: '{{ wo_basedir }}/tools'
      remote_src: true
      owner: '{{ wo_user }}'
      group: '{{ wo_user_group }}'
      mode: 0755

  - name: 'JavaMonitor | Rename JavaMonitor bundle'
    shell: mv JavaMonitor-*.woa JavaMonitor.woa
    args:
      chdir: '{{ wo_basedir }}/tools'
  when: javamonitor_dir.stat.exists == False

- name: 'JavaMonitor | Fetch Java version'
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- name: 'JavaMonitor | Configure the JavaMonitor to run with Java >= 9'
  lineinfile:
    path: '{{ wo_basedir }}/tools/JavaMonitor.woa/Contents/{{ item }}'
    regexp: '^# JVMOptions'
    line: '# JVMOptions       == --add-exports java.base/sun.security.action=ALL-UNNAMED'
  with_items:
    - 'UNIX/UNIXClassPath.txt'
    - 'MacOS/MacOSClassPath.txt'
    - 'MacOS/MacOSXServerClassPath.txt'
    - 'Windows/CLSSPATH.TXT'
  when: java_version.stdout is version_compare('9', '>=')