# Main file for ansible-webobjects-role
---
- import_tasks: prepare.yml
  become: yes
  become_user: root
- import_tasks: adaptor.yml
  when: wo_install_apache_adaptor == True
  tags:
    - wo
    - apache
    - adaptor
- import_tasks: deploy.yml
  tags:
    - wo
    - deploy
- import_tasks: wotaskd.yml
  when: wo_install_wotaskd == True
  tags:
    - wo
    - deploy
    - wotaskd
- import_tasks: javamonitor.yml
  when: wo_install_javamonitor == True
  tags:
    - wo
    - deploy
    - java_monitor
- import_tasks: configure.yml
  tags:
    - wo
    - service