# Main file for ansible-webobjects-role
---
- import_tasks: prepare.yml
  become: yes
  become_user: root
- import_tasks: adaptor.yml
  tags:
    - wo
    - apache
    - adaptor
- import_tasks: deploy.yml
  tags:
    - wo
    - deploy
    - wotaskd
    - java_monitor
- import_tasks: configure.yml
  tags:
    - wo
    - service