# prepare file for ansible-webojects-role
# Here should go tasks that will prepare the system, environment, etc, before the installation continues
---
- name: 'PREPARE | Install required tools (Git, Make, GCC, httpd-devel)'
  yum:
    name:
      - 'vim'
      - 'git'
      - 'make'
      - 'gcc'
      - 'httpd'
      - 'httpd-devel'
      # Oracle Linux 8 dependency
      - 'redhat-rpm-config'
      - '{{ java_version }}'
    state: present

- name: 'PREPARE | Create {{ wo_user_group }} group in the system'
  group:
    name: '{{ wo_user_group }}'
    state: present

- name: 'PREPARE | Create {{ wo_user }} user in the system'
  user:
    name: "{{ wo_user }}"
    state: present
    comment: "{{ wo_name }} applications administrator user"
    group: "{{ wo_user_group }}"
    createhome: yes
    home: '{{ wo_user_homedir }}'

- name: 'PREPARE | Enable the wotaskd log when starting apps'
  file:
    path: '/tmp/logWebObjects'
    owner: 'root'
    group: 'root'
    state: touch

- name: 'DEPLOY | Create {{ wo_name }} related directories'
  file:
    path: '{{ item }}'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: directory
    mode: 0755
  with_items:
    - '{{ wo_basedir }}/tools'
    - '{{ wo_basedir }}/apps'
    - '{{ wo_basedir }}/config'
    - '{{ wo_logdir }}'
    - '{{ wo_logdir }}/gc'
    - '{{ wo_logdir }}/heapdumps'

- name: 'DEPLOY | Create directory for {{ wo_name }} web resources'
  file:
    path: '{{ wo_webdir }}'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: directory
    mode: 0755

- name: 'PREPARE | Ensure WOTaskD log file is created'
  file:
    path: '{{ wo_logdir }}/wotaskd.log'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: touch
  when: wo_install_wotaskd == True

- name: 'PREPARE | Ensure JavaMonitor log file is created'
  file:
    path: '{{ wo_logdir }}/JavaMonitor.log'
    owner: '{{ wo_user }}'
    group: '{{ wo_user_group }}'
    state: touch
  when: wo_install_javamonitor == True
