---
- name: 'WOTASKD | Check if wotaskd is already installed'
  stat:
    path: '{{ wo_basedir }}/tools/wotaskd.woa'
  register: wotaskd_dir

- block:
  - name: 'WOTASKD | Download the latest version of wotaskd'
    unarchive:
      src: '{{ wotaskd_download_url }}'
      dest: '{{ wo_basedir }}/tools'
      remote_src: true
      owner: '{{ wo_user }}'
      group: '{{ wo_user_group }}'
      mode: 0755

  - name: 'WOTASKD | Rename wotaskd bundle'
    shell: mv wotaskd-*.woa wotaskd.woa
    args:
      chdir: '{{ wo_basedir }}/tools'
  when: wotaskd_dir.stat.exists == False

- name: 'WOTASKD | Configure the wotaskd log file when starting apps'
  lineinfile:
    path: '{{ wo_basedir }}/tools/wotaskd.woa/Contents/Resources/SpawnOfWotaskd.sh'
    regexp: '^LOG='
    line: LOG='{{ wo_logdir }}/SpawnOfWotaskd.log'

- name: 'WOTASKD | Fetch Java version'
  shell: java -version 2>&1 | grep version | awk '{print $3}' | sed 's/"//g'
  register: java_version

- name: 'WOTASKD | Configure the wotaskd to run with Java >= 9'
  lineinfile:
    path: '{{ wo_basedir }}/tools/wotaskd.woa/Contents/{{ item }}'
    regexp: '^# JVMOptions'
    line: '# JVMOptions       == --add-exports java.base/sun.security.action=ALL-UNNAMED'
  with_items:
    - 'UNIX/UNIXClassPath.txt'
    - 'MacOS/MacOSClassPath.txt'
    - 'MacOS/MacOSXServerClassPath.txt'
    - 'Windows/CLSSPATH.TXT'
  when: java_version.stdout is version_compare('9', '>=')