---
- name: 'HANDLER | Restart httpd'
  service:
    name: httpd
    state: restarted
  listen:
    - restart_httpd
    - restart_apache

- name: 'HANDLER | Reload SystemD units'
  systemd:
    daemon_reload: yes
  listen:
    - start_wo_unit
    - start_wo
    - restart_wo

- name: "HANDLER | Restart {{ wo_name }}'s (and enable if needed) WOTaskD"
  service:
    name: 'wotaskd'
    state: restarted
    enabled: yes
  when: wo_start_wotaskd == True
  listen:
    - start_wo_unit
    - start_wo
    - restart_wo

- name: "HANDLER | Start {{ wo_name }}'s (and enable if needed) JavaMonitor"
  service:
    name: 'javamonitor'
    state: restarted
    enabled: yes
  when: wo_start_javamonitor == True
  listen:
    - start_javamonitor_service
    - javamonitor_service
    - restart_javamonitor
