---
- name: 'HANDLER | Restart httpd'
  service:
    name: httpd
    state: restarted
  listen:
    - restart_httpd
    - restart_apache

- name: 'HANDLER | Reload SystemD units'
  systemd:
    daemon_reload: yes
  listen:
    - start_wo_unit
    - start_wo
    - restart_wo

- name: 'HANDLER | Restart {{ wo_name }}'
  service:
    name: '{{ wo_name }}'
    state: restarted
    enabled: yes
  listen:
    - start_wo_unit
    - start_wo
    - restart_wo

- name: 'HANDLER | Start JavaMonitor'
  service:
    name: 'javamonitor'
    state: restarted
    enabled: yes
  when: wo_start_javamonitor == True
  listen:
    - start_javamonitor_service
    - javamonitor_service
    - restart_javamonitor

- name: 'HANDLER | Disable JavaMonitor'
  service:
    name: 'javamonitor'
    state: stopped
    enabled: false
  when: wo_start_javamonitor == False
  listen:
    - start_javamonitor_service
    - javamonitor_service
    - restart_javamonitor
