---
- name: 'HANDLER | Restart httpd'
  service:
    name: httpd
    state: restarted
  listen: restart_httpd

- name: 'HANDLER | Restart {{ wo_name }}'
  service:
    name: '{{ wo_name }}'
    state: started
    enabled: yes
  listen: start_wo_unit